ParkYamManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('ParkYamManagerApp.urls')),
    #url(r'^$', include('ParkYamManagerApp.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

admin.site.site_header = 'ParkYamManager administration'

ParkYamManagerApp/urls.py
from django.conf.urls import url
import views
from views import MessageListView
from views import UnrepliedMessageListView
from django.views.generic import TemplateView

app_name = 'app'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^roomscleaning/$', views.rooms_cleaning, name='rooms_cleaning'),
    url(r'^roomscleaning/(?P<room_number>[0-9]+)/$', views.detail, name='detail'),
    url(r'^roomscleaning/(?P<room_number>[0-9]+)/set_clean/$', views.set_clean, name='set_clean'),

    url(r'^roomsmaintenance/$', views.rooms_maintenance, name='rooms_maintenance'),
    url(r'^roomsmaintenance/(?P<room_number>[0-9]+)/$', views.room_maintenance_details, name='room_maintenance_details'),
    url(r'^roomsmaintenance/(?P<room_number>[0-9]+)/set_room_maintenance_status/$', views.set_room_maintenance_status, name='set_room_maintenance_status'),

    url(r'^roomsummary/$', views.rooms_summary, name='rooms_summary'),

    url(r'^sendmessage/$', views.send_message, name='send_message'),
    url(r'^messages/$', MessageListView.as_view(), name='messages'),
    url(r'^pending_messages/$', UnrepliedMessageListView.as_view(), name='pending_messages'),
    url(r'^reply/(?P<message_id>[0-9]+)/$', views.reply_message, name='reply'),

    url(r'^reception/$', views.reception, name = 'reception'),
	url(r'^reception/(?P<room_number>[0-9]+)/$', views.room_reception_details, name='room_reception_details'),
    url(r'^shifts/$', views.shift, name='shifts'),
    url(r'^shifts/calculate_shifts$', views.calculate_shifts, name="calculate_shifts"),
    url(r'^schedule/$', views.current_shift, name='schedule'),

    url(r'^staff', TemplateView.as_view(template_name=r'app/staff.html'),name='staff'),

]

ParkYamManagerApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.forms import ModelForm
from django.core.exceptions import ValidationError

# Create your models here.

class Room(models.Model):
    number = models.IntegerField("Room Number", primary_key = True)
    floor = models.IntegerField("Room Floor")
    room_size = models.IntegerField("Room Size (Square Meter)")
    bathroom_size = models.IntegerField("Bathroom Size (Square Meter)")
    double_beds_count = models.IntegerField("Double Beds Count", default = 1)
    single_beds_count = models.IntegerField("Single Beds Count",default = 0)

    BATHROOM_TYPE = (
        (0, 'Bathtub'),
        (1, 'Shower'),
    )

    bathroom_type = models.IntegerField("Bathroom Type", choices = BATHROOM_TYPE, default = 'Shower')

    is_suite = models.BooleanField("Suite", default = False)
    is_seaview = models.BooleanField("Sea View", default = False)
    is_place_for_crib = models.BooleanField("Has Place For Crib", default = True)
    is_clean = models.BooleanField("Clean", default=True)
    clean_comment = models.CharField("Clean_comment",max_length=1000,default="")
    is_room_being_cleaned = models.BooleanField("Is Room Being Cleaned", default=False)

    needs_maintenance = models.BooleanField("NeedsMaintenance", default=False)
    maintenance_comment = models.CharField("MaintenanceComment", max_length=1000, default="")

    class Meta:
        permissions = (
            ("maintain_room", "Can maintain room"),
            ("clean_room", "Can clean room"),
            ("view_room_status", "Can view room status"),
        )

class Message(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField("Message", default="")
    reply = models.TextField("Reply", default="", blank=True)
    replier_name = models.CharField("Replier", max_length = 255, default="", blank=True)
    message_time = models.DateTimeField("Message Time", auto_now=True)

    class Meta:
        permissions = (("can_send_message", "Can send message"), ("can_reply_message", "Can reply message"))

    def __str__(self):
        return '%s   %s   %s' % (self.user, self.message_time.strftime('%d-%m-%Y %H:%M:%S'), self.message[:20])

class SendMessageForm(ModelForm):
    def clean_message(self):
        data = self.cleaned_data['message']

        #Check message is not empty
        if not data:
            raise ValidationError('Message cannot be empty')

        return data

    class Meta:
        model = Message
        fields = ['message']
        #help_texts = {'message': ('Enter a message'), }

class ReplyMessageForm(ModelForm):
    def clean_message(self):
        data = self.cleaned_data['message']

        #Check message is not empty
        if not data:
            raise ValidationError('Message cannot be empty')

        return data

    class Meta:
        model = Message
        fields = ['message', 'user', 'reply', 'replier_name']
        #help_texts = {'message': ('Enter a message'), }

times = [
    (0, 'OFF_Morning'),
    (1, 'OFF_Afternoon'),
    (2, 'OFF_Night'),
    (3, 'Off_ALL_DAY'),
    (4, 'Off_Morning_Afternoon'),
    (5, 'Off_AftNoon_Night'),
    (6, 'Off_Morning_Night'),
    (7, 'General'),
]

days = [
    (0, 'Sunday'),
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday')
]


class Shift(models.Model):

    id = models.IntegerField("id", primary_key=True)
    worker_name = models.CharField("Name", max_length=255, default="Type your name in here")
    sunday = models.IntegerField("Sunday", choices=times, default='7')
    monday = models.IntegerField("Monday", choices=times, default='7')
    tuesday = models.IntegerField("Tuesday", choices=times, default='7')
    wednesday = models.IntegerField("Wednesday", choices=times, default='7')
    thursday = models.IntegerField("Thursday", choices=times, default='7')
    friday = models.IntegerField("Friday", choices=times, default='7')
    saturday = models.IntegerField("Saturday", choices=times, default='7')

    comment = models.CharField("Comment", max_length=255, default="Type here any comments")

    # class Meta:
    #     permissions = (("can_send_message", "Can send message"), ("can_reply_message", "Can reply message"))

    def __str__(self):
        return '%d' % (self.id)


class ReceptionWorker(models.Model):
    id = models.IntegerField("id", primary_key=True)
    worker_name = models.CharField("Name", max_length=255, default="worker name")

class ShiftAssignment(models.Model):
    id = models.IntegerField("id", primary_key=True)
    worker_name = models.CharField("Name", max_length=255, default="worker name")


class ShiftForm(ModelForm):
    def clean_message(self):
        data = self.cleaned_data['hello']

        #Check message is not empty
        if not data:
            raise ValidationError('Form cannot be empty')

        return data

    class Meta:
        model = Shift
        fields = ['worker_name','sunday','monday','tuesday','wednesday','thursday','friday','saturday','comment']

ParkYamManagerApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from .models import Room
from .models import Message
from .models import SendMessageForm
from .models import ReplyMessageForm
from .models import ReceptionWorker
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.views import generic
from django.utils.decorators import method_decorator
from .models import Shift
from .models import ShiftAssignment
from .models import ShiftForm
# Create your views here.

def home(request):
    return render(request,"app/home.html")

def get_rooms_floors():
    rooms = Room.objects.all()
    rooms_floors = set(map(lambda room: room.floor, rooms))
    return rooms_floors

def get_rooms_by_floor(request):
    rooms = Room.objects.all()

    rooms_floors = get_rooms_floors()

    floor_filter = 0
    try:
        floor_filter = int(request.GET.get('floor', False))
    except ValueError:
        pass

    rooms_by_floor = [[] for i in rooms_floors]
    for room in rooms:
        if floor_filter:
            if room.floor != floor_filter:
                continue
            else:
                rooms_by_floor[0].append(room)
        else:
            rooms_by_floor[room.floor - 1].append(room)
    return rooms_by_floor

@permission_required('ParkYamManagerApp.clean_room')
def rooms_summary(request):
    rooms = Room.objects.all()
    context = {'rooms': rooms}
    return render(request, 'app/rooms_summary.html', context)

@permission_required('ParkYamManagerApp.clean_room')
def rooms_cleaning(request):
    rooms_by_floor = get_rooms_by_floor(request)
    number_of_floors = len(get_rooms_floors())
    context = {'rooms_by_floor': rooms_by_floor, 'number_of_floors': xrange(1, number_of_floors+1)}
    return render(request, 'app/rooms_cleaning.html', context)

@permission_required('ParkYamManagerApp.maintain_room')
def rooms_maintenance(request):
    rooms_by_floor = get_rooms_by_floor(request)
    number_of_floors = len(get_rooms_floors())
    context = {'rooms_by_floor': rooms_by_floor, 'number_of_floors': xrange(1, number_of_floors+1)}
    return render(request, 'app/rooms_maintenance.html', context)

@permission_required('ParkYamManagerApp.view_room_status')
def reception(request):
    rooms = Room.objects.all()
    rooms_by_floor = [[] for i in xrange(6)]
    for room in rooms:
        rooms_by_floor[room.floor-1].append(room)
    for rooms in rooms_by_floor:
        rooms.sort(key=lambda x:x.number)
    context = {'rooms_by_floor': rooms_by_floor}
    return render(request, 'app/reception.html', context)

@permission_required('ParkYamManagerApp.change_room')
def detail(request, room_number):
    room = get_object_or_404(Room, pk=room_number)
    return render(request, 'app/detail.html', {'room': room, 'comment_value':room.clean_comment})

@permission_required('ParkYamManagerApp.maintain_room')
def room_maintenance_details(request, room_number):
    room = get_object_or_404(Room, pk=room_number)
    return render(request, 'app/room_maintenance_details.html', {'room': room, 'comment_value':room.maintenance_comment})

@permission_required('ParkYamManagerApp.view_room_status')
def room_reception_details(request, room_number):
    room = get_object_or_404(Room, pk=room_number)
    return render(request, 'app/room_reception_details.html', {'room': room})


@permission_required('ParkYamManagerApp.change_room')
def set_clean(request, room_number):
    room = Room.objects.get(number=room_number)
    try:
        selected_choice = request.POST['choice']
        clean_comment = request.POST['clean_comment']
    except KeyError:
        return render(request, 'app/detail.html', {
            'room': room,
            'error_message': "You didn't select a choice.",
        })
    room.clean_comment = clean_comment
    if selected_choice == "clean":
        room.is_clean = True
        room.is_room_being_cleaned = False
        room.save()
    elif selected_choice == "not clean":
        room.is_clean = False
        room.is_room_being_cleaned = False
        room.save()
    elif selected_choice== "in progress":
        room.is_clean = False
        room.is_room_being_cleaned = True
        room.save()
    else:
        return HttpResponse("Error 2")
    return HttpResponseRedirect(reverse('app:rooms_cleaning'))

@permission_required('ParkYamManagerApp.maintain_room')
def set_room_maintenance_status(request, room_number):
    room = Room.objects.get(number=room_number)
    try:
        selected_choice = request.POST['choice']
        maintenance_comment = request.POST['maintenance_comment']
    except KeyError:
        return render(request, 'app/room_maintenance_details.html', {
            'room': room,
            'error_message': "You didn't select a choice.",
        })
    room.maintenance_comment = maintenance_comment
    if selected_choice == "need maintenance":
        room.needs_maintenance = True
        room.save()
    elif selected_choice == "does not need maintenance":
        room.needs_maintenance = False
        room.save()
    else:
        return HttpResponse("Error 2")
    return HttpResponseRedirect(reverse('app:rooms_maintenance'))


@permission_required('ParkYamManagerApp.can_send_message')
def send_message(request):
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        message = Message()
        message.user = request.user

        # Create a form instance and populate it with data from the request (binding):
        form = SendMessageForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            message.message = form.cleaned_data['message']
            message.save()

            # redirect to a new URL:
            return render(request, 'app/message_sent.html')

    # If this is a GET (or any other method) create the default form.
    else:
        form = SendMessageForm()

    return render(request, 'app/send_message.html', {'form': form})

class MessageListView(generic.ListView):
    model = Message
    template_name = 'app/user_messages.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MessageListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Message.objects.filter(user=self.request.user).order_by('-message_time')

class UnrepliedMessageListView(generic.ListView):
    model = Message
    template_name = 'app/unreplied_messages.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UnrepliedMessageListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Message.objects.filter(reply__exact='').order_by('-message_time')

@permission_required('ParkYamManagerApp.can_delete_room')
def shift(request):
    workers = ReceptionWorker.objects.all()
    return render(request,"app/shift.html", {'workers': workers})

@permission_required('ParkYamManagerApp.can_delete_room')
def calculate_shifts(request):
    # print request.POST
    class Shift:
        def __init__(self, id, next, prev, po_list):
            self.id = id
            self.next = next
            self.prev = prev
            self.po_list = po_list[:]

    def solve_r(shifts, ac):  # assigned_counter
        if len(shifts) == 0:
            return True
        x = [len(i.po_list) for i in shifts]
        cur = shifts[x.index(min(x))]
        opts = cur.po_list
        opts.sort(key=lambda x: ac[x])
        for opt in opts:
            if cur.next and opt in cur.next.po_list:
                cur.next.po_list.remove(opt)
                was_in_next = True
            else:
                was_in_next = False

            if cur.prev and opt in cur.prev.po_list:
                cur.prev.po_list.remove(opt)
                was_in_prev = True
            else:
                was_in_prev = False
            shifts.remove(cur)
            cur.worker = opt
            ac[opt] += 1
            if solve_r(shifts, ac):
                return True
            ac[opt] -= 1
            shifts.append(cur)
            if was_in_next:
                cur.next.po_list.append(opt)
            if was_in_prev:
                cur.prev.po_list.append(opt)
        return False

    def solve(shifts, ac):
        return solve_r(shifts[:], ac)

    workers = ReceptionWorker.objects.all()
    ac = [0] * len(workers)
    shifts = [Shift(i, None, None, [j for j in xrange(len(workers)) if u"%d_%d"%(j,i) in request.POST]) for i in xrange(21)]
    for i in xrange(21):
        if i != 20:
            shifts[i].next = shifts[i + 1]
        if i != 0:
            shifts[i].prev = shifts[i - 1]

    if True == solve(shifts, ac):
        #Delete previous result
        ShiftAssignment.objects.all().delete()

        sol = [None]*21
        for s in shifts:
            sol[s.id] = ReceptionWorker.objects.get(id=s.worker).worker_name
            shift_assignment = ShiftAssignment()
            shift_assignment.id = s.id
            shift_assignment.worker_name = sol[s.id]
            shift_assignment.save()
        return render(request, "app/shift_assignment.html", {'sol': sol})
    else:
        return render(request, "app/shift_assignment_error.html")
def get_schedule(request):
    shifts = Shift.objects.all()

    times = [
        'Morning',
        'Afternoon',
        'Night',
        'OFF_Morning',
        'OFF_Afternoon',
        'OFF_Night',
        'OFF_Morning_Afternoon',
        'OFF_AftNoon_Night',
        'OFF_Morning_Night',
        'OFF_ALL_DAY',
    ]

    shift_org = {}
    shift_org[0] =[0,4,6,3]
    shift_org[1] = [1,4,5,3]
    shift_org[2] = [2,6, 5, 3]
    #
    # coms = {}
    # shifts = Shift.objects.all()
    # for obj in shifts:

ParkYamManagerApp/templates/app/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Park Yam</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><img src="{% static 'images/logo.png' %}" alt="Logo" width="150" border="0"/></li>

          {% if user.is_authenticated %}
            <li><b>Hello {{ user.get_username }}!</b></li>
            <br><br>

            <li><img src="{% static 'images/home-icon.jpg' %}" width="25"><a href="{% url 'app:home' %}">   Home</a></li>
            <li><img src="{% static 'images/contact.png' %}" width="25"><a href="{% url 'app:staff' %}">   Staff & Management contact info </a></li>
            <!-- instead of defining specifc permission for admin only-->
           {% if perms.ParkYamManagerApp.can_delete_room %}
                <li><img src="{% static 'images/empty-calendar-icon.png' %}" width="25"><a href="{% url 'app:shifts' %}">   Create Shifts</a></li>
            {% endif %}

           {% if perms.ParkYamManagerApp.view_room_status %}
                <li><img src="{% static 'images/calendar-icon.png' %}" width="25"><a href="{% url 'app:schedule' %}">   Shifts Schedule</a></li>
                <li><img src="{% static 'images/room-icon.png' %}" width="25"><a href="{% url 'app:reception' %}">  Rooms (Reception)</a></li>
            {% endif %}
            {% if perms.ParkYamManagerApp.change_room %}
                <li><img src="{% static 'images/broom-icon.jpg' %}" width="25"><a href="{% url 'app:rooms_cleaning' %}">    Rooms Cleaning</a></li>
            {% endif %}
            {% if perms.ParkYamManagerApp.maintain_room %}
                <li><img src="{% static 'images/hammer-icon.png' %}" width="25"><a href="{% url 'app:rooms_maintenance' %}">    Rooms Maintenance</a></li>
            {% endif %}
                <li><img src="{% static 'images/summary-icon.jpg' %}" width="25"><a href="{% url 'app:rooms_summary' %}">   Rooms Summary</a></li>
            {% if perms.ParkYamManagerApp.can_send_message %}
                {% if perms.ParkYamManagerApp.can_delete_room %}
                    <li><img src="{% static 'images/reply-icon.png' %}" width="25"><a href="{% url 'app:pending_messages' %}">   Pending Messages</a></li>
                {% else %}
                    <li><img src="{% static 'images/messages-icon.jpg' %}" width="25"><a href="{% url 'app:messages' %}">   Messages List</a></li>
                    <li><img src="{% static 'images/sent-icon.jpg' %}" width="25"><a href="{% url 'app:send_message' %}">   Send Message</a></li>
                {% endif %}
            {% endif %}



            <li><img src="{% static 'images/logout-icon.jpg' %}" width="25"><a href="{% url 'logout'%}?next={{request.path}}">  Logout</a></li>
          {% else %}
             <li><img src="{% static 'images/login-icon.jpg' %}" width="25"><a href="{% url 'login'%}?next={{request.path}}">   Login</a></li>
           {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

ParkYamManagerApp/templates/app/detail.html
{% extends "app/base_generic.html" %}

{% block content %}
<h1>Room {{ room.number }} {% if comment_value %}({{ comment_value }}){% endif %}</h1>
{% if room.is_clean %}<h2><font color="green">The room is clean</font></h2>
{% else %} <h2> <font color="red">The room is not clean</font></h2>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app:set_clean' room.number%}" method="post">
{% csrf_token %}

    <input type="radio" name="choice" id="clean" value="clean" />
    <label for="clean">clean</label><br />
    <input type="radio" name="choice" id="in progress" value="in progress" />
    <label for="in progress">in progress</label><br />
    <input type="radio" name="choice" id="not clean" value="not clean" />
    <label for="not clean">not clean</label><br />
    Comment: <input type="text" name="clean_comment" value="{{ comment_value }}">
<input type="submit" value="Send" />
</form>

{% endblock %}

ParkYamManagerApp/templates/app/index.html
{% if rooms %}
    <ul>
    {% for room in rooms %}
        <li><a href="{% url 'app:detail' room.number %}">{{ room.number }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Rooms are available.</p>
{% endif %}

ParkYamManagerApp/templates/app/message_sent.html
{% extends "app/base_generic.html" %}
{% block content %}
<h1><br><br></h1>
  {% load static %}
        <img src="{% static 'images/message_sent_pic.png' %}" alt="Message sent"/>
{% endblock %}

ParkYamManagerApp/templates/app/reception.html
{% extends "app/base_generic.html" %}

{% block content %}
<div align="center">
<h1> List of rooms </h1>
</div>
{% if rooms_by_floor %}
    <ul>
	<div align="center">
	<table border="1">
	{% for floor_rooms in rooms_by_floor %}
	<tr height="70">
    {% for room in floor_rooms %}
		{% if not room.needs_maintenance and room.is_clean %}<td bgcolor="#80ff80" width="70">
		{% else %}<td bgcolor="#ff8080" width="70">
		{% endif %}
		<div align="center">
        <h4><b><a href="{% url 'app:room_reception_details' room.number %}"> {{ room.number }}</a></b></h4>
		{% if not room.is_clean %} <i class="glyphicon glyphicon-tree-conifer" style="color:red;" title="{{ room.clean_comment }}"></i>
		{% else %} <i class="glyphicon glyphicon-tree-conifer" style="color:green;" title="{{ room.clean_comment }}"></i>
		{% endif %}
		
		{% if room.needs_maintenance %} <i class="glyphicon glyphicon-wrench" style="color:red;" title="{{ room.maintenance_comment }}"></i>
		{% else %} <i class="glyphicon glyphicon-wrench" style="color:green;" title="{{ room.maintenance_comment }}"></i>
		{% endif %}
		
		{% if room.double_beds_count %} <i class="glyphicon glyphicon-bed" title="{{ room.double_beds_count }}"></i> {% endif %}
		
		</div>
		</td>
    {% endfor %}
	</tr>
	{% endfor %}
	</table>
	</div>
    </ul>
{% else %}
    <p>No Rooms are available.</p>
{% endif %}
{% endblock %}

ParkYamManagerApp/templates/app/room_reception_details.html
{% extends "app/base_generic.html" %}

{% block content %}
<h1>Room {{ room.number }}</h1>
{% if not room.needs_maintenance%}<h2><font color="green">The room does not need maintenace</font></h2>
{% else %} <h2> <font color="red">The room needs maintenace</font></h2>
{% endif %}

{% if room.is_clean%}<h2><font color="green">The room is clean</font></h2>
{% else %} <h2> <font color="red">The room is not clean</font></h2>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% endblock %}

ParkYamManagerApp/templates/app/rooms_cleaning.html
{% extends "app/base_generic.html" %}

{% block content %}
<div align="center">
<h1>Rooms Cleaning</h1>
<table border="1">
	<tr height="70">
		<td bgcolor="#DCDCDC" width="70">
			<div align="center"><h3><a href="?floor=0">All</a></h3></div>
		</td>
		{% for floor_number in number_of_floors %}
		<td bgcolor="#DCDCDC" width="70">
			<div align="center"><h3><a href="?floor={{ floor_number }}">{{ floor_number }}</a></h3></div>
		</td>
		{% endfor %}
	</tr>
</table>
<br />
	{% if rooms_by_floor %}
	<table border="1">
	{% for floor_rooms in rooms_by_floor %}
	<tr height="70">
    {% for room in floor_rooms %}
		{% if room.is_room_being_cleaned %}<td bgcolor="#ffff33" width="70">
		{% elif room.is_clean %}<td bgcolor="#00ff00" width="70">
		{% else %}<td bgcolor="#ff5050" width="70">
		{% endif %}
        <div align="center"><h3><a href="{% url 'app:detail' room.number %}">{{ room.number }}</a></h3></div>
		</td>
    {% endfor %}
	</tr>
	{% endfor %}
	</table>
{% else %}
    <p>No Rooms are available.</p>
{% endif %}
</div>
{% endblock %}

ParkYamManagerApp/templates/app/rooms_maintenance.html
{% extends "app/base_generic.html" %}

{% block content %}
<div align="center">
<h1>Rooms Maintenance</h1>
<table border="1">
	<tr height="70">
		<td bgcolor="#DCDCDC" width="70">
			<div align="center"><h3><a href="?floor=0">All</a></h3></div>
		</td>
		{% for floor_number in number_of_floors %}
		<td bgcolor="#DCDCDC" width="70">
			<div align="center"><h3><a href="?floor={{ floor_number }}">{{ floor_number }}</a></h3></div>
		</td>
		{% endfor %}
	</tr>
</table>
<br />
{% if rooms_by_floor %}
	<table border="1">
	{% for floor_rooms in rooms_by_floor %}
	<tr height="70">
    {% for room in floor_rooms %}
		{% if not room.needs_maintenance %}<td bgcolor="#00ff00" width="70">
		{% else %}<td bgcolor="#ff5050" width="70">
		{% endif %}
        <div align="center"><h3><a href="{% url 'app:room_maintenance_details' room.number %}">{{ room.number }}</a></h3></div>
		</td>
    {% endfor %}
	</tr>
	{% endfor %}
	</table>
{% else %}
    <p>No Rooms are available.</p>
{% endif %}
</div>
{% endblock %}

ParkYamManagerApp/templates/app/rooms_summary.html
{% extends "app/base_generic.html" %}

{% block content %}
<div align="center">
    <h1>Rooms Summary</h1>
    <table border="1" width="80%">
        <tr>
            <th>Room #</th>
            <th>Maintenance Comment</th>
            <th>Cleaning Comment</th>
        </tr>
    {% for room in rooms %}
        {% if room.needs_maintenance or not room.is_clean %}
        <tr height="70">
            <td><div align="center"><h3>{{ room.number }}</h3></div></td>
            <td>{{ room.maintenance_comment }}</td>
            <td>{{ room.clean_comment }}</td>
        </tr>
        {% endif %}
    {% endfor %}
    </table>
</div>
{% endblock %}